### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by uppittu11** [daico007/Scipy2020-MoSDeF#1]
Complete workflow: mbuild -> foyer -> parmed -> GMSO -> GROMACS 

**mbuild:**
- [x]  Small molecules in a box (user can select a molecule using SMILES string or from a pdb files (provided))

**foyer:**
- [x] Typed with the GAFF package
- [x] Charge assignment with antefoyer
- [x] Return a parmed structure 

**GMSO:**
- [x] Convert the parmed structure to a GMSO Topology
- [x] Show case the way parameters are stored (**unyt**, **expressions**)
- [x] Save out to `.gro` and `.top` 
(Need to add whatever form used on GAFF to the `accepted_potentials`: https://github.com/mosdef-hub/gmso/blob/3d363fc8bde5984b97e7c71ef36e9ea0c49e1e3e/gmso/formats/top.py#L235) 

**GROMACS:**
- [x] Run the simulation of the box for a bit and show energy? 

**General**
- [ ] Add image in the README
- [ ] Switch out molecules and reduce number of molecules
- [x] Make the notebook a binder
